// Generated by CoffeeScript 1.6.3
(function() {
  var Path, async, found_css_dep, fs, scan_code;

  async = require('async');

  Path = require('./path');

  fs = require('fs');

  found_css_dep = function(orig, ext, path) {
    var _this = this;
    return function(cb) {
      return _this.pipeline.compile_file(path, function(err, res) {
        var cachedname, filename;
        if (err) {
          return cb(err);
        }
        _this.pipeline.depmgr.depends_on(_this.pipeline.path_to_req(orig), path);
        filename = _this.pipeline.path_to_req(path);
        cachedname = _this.pipeline.req_to_cache(filename);
        return fs.readFile(cachedname, 'utf8', function(err, data) {
          if (err) {
            return cb(err);
          }
          return scan_code.call(_this, data, ext, filename, cb);
        });
      });
    };
  };

  scan_code = function(code, ext, filename, cb) {
    var dir, file, funcs, imports, matches, path, _i, _len, _ref, _ref1,
      _this = this;
    ext = '.' + ext.replace(/^\./, '');
    dir = Path.dirname(filename);
    funcs = [];
    matches = code.match(/^@import\s.*$/mg);
    if (matches != null) {
      _ref = code.match(/^@import\s.*$/mg);
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        imports = _ref[_i];
        file = (_ref1 = imports.match(/^@import\s+'([^']+)'/)) != null ? _ref1 : imports.match(/^@import\s+"([^"]+)"/);
        if (file) {
          file = file[1];
          if (ext !== Path.extname(file)) {
            file = file + ext;
          }
          path = this.pipeline.path_to_req(Path.join(dir, file));
          if (!path.match(/^\.\.\//)) {
            funcs.push(found_css_dep.call(this, filename, ext, path));
          }
        }
      }
    }
    return async.parallel(funcs, function(err, res) {
      if (err) {
        return cb(err);
      } else {
        if (funcs.length > 0) {
          filename = _this.pipeline.path_to_cache(filename);
          return require('./util').write_file(filename, code, function(err) {
            return cb(err, filename);
          });
        } else {
          return cb(null, filename);
        }
      }
    });
  };

  module.exports.search_deps = function(code, options, ext, cb) {
    return scan_code.call(options, code, ext, options.filename, cb);
  };

}).call(this);
