// Generated by CoffeeScript 1.2.1-pre
(function() {
  var Path, calc, fs, mappings, util;

  Path = require('path');

  fs = require('fs');

  util = require('./util');

  mappings = {};

  module.exports.setmappings = function setmappings(map) {
    return mappings = map;
  };

  module.exports.calc = calc = function calc(from, to, oldpath, seen) {
    var ext, min, minpath, newext, newfrom, newpath, res, _i, _len, _ref;
    if (oldpath == null) oldpath = [];
    if (seen == null) seen = {};
    if (oldpath.length > 10) return null;
    if (seen[from]) return null;
    seen[from] = 1;
    if (from === to) return oldpath;
    ext = Path.extname(from);
    if (ext === '' || !(mappings[ext] != null)) return null;
    newfrom = Path.basename(from, ext);
    min = Infinity;
    minpath = null;
    _ref = mappings[ext];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      newext = _ref[_i];
      newpath = oldpath.slice(0).concat({
        ext: ext,
        file: newfrom + newext
      });
      res = calc(newfrom + newext, to, newpath, seen);
      if ((res != null) && res.length < min) {
        min = res.length;
        minpath = res;
      }
    }
    return minpath;
  };

  module.exports.find = function find(path, file, maincb) {
    var base, beginning, dir, search_for;
    search_for = Path.join(path, file);
    base = Path.basename(search_for);
    beginning = base.substr(0, base.indexOf('.')) || base;
    dir = Path.dirname(search_for);
    return fs.readdir(dir, function(err, files) {
      var error, found, foundfile, makepath, results, x, _i, _j, _len, _len2, _ref;
      if (err) return maincb(err);
      results = [];
      found = {
        path: '',
        extlist: []
      };
      for (_i = 0, _len = files.length; _i < _len; _i++) {
        foundfile = files[_i];
        if (!(foundfile.indexOf(beginning) === 0)) continue;
        makepath = calc(foundfile, base);
        if ((makepath != null) && found.extlist.length <= makepath.length) {
          found.path = Path.join(Path.dirname(search_for), foundfile);
          found.extlist = makepath;
          _ref = found.extlist;
          for (_j = 0, _len2 = _ref.length; _j < _len2; _j++) {
            x = _ref[_j];
            x.file = Path.join(dir, x.file);
          }
        }
      }
      if (found.path === '') {
        error = new Error('File not found: ' + file);
        error.code = 'asset-pipeline/filenotfound';
        return maincb(error);
      } else {
        return maincb(err, found);
      }
    });
  };

}).call(this);
