// Generated by CoffeeScript 1.6.3
(function() {
  var Path, dewindoze, func, _i, _len, _ref;

  Path = require('path');

  dewindoze = function(fn) {
    return function() {
      return fn.apply(null, arguments).replace(/^[A-Z]:\\/, '\\').replace(/\\/g, '/');
    };
  };

  if (require('os').platform() !== 'win32') {
    module.exports = Path;
  } else {
    _ref = ['basename', 'dirname', 'extname', 'join', 'normalize', 'relative', 'resolve'];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      func = _ref[_i];
      module.exports[func] = dewindoze(Path[func]);
    }
  }

}).call(this);
