// Generated by CoffeeScript 1.2.1-pre
(function() {
  var MakePath, Path, fs;

  fs = require('fs');

  Path = require('path');

  MakePath = require('./makepath');

  module.exports.load = function load() {
    var ext, filename, mappings, name, plugin, plugins, te, _i, _j, _k, _len, _len2, _len3, _ref, _ref2, _ref3;
    plugins = {};
    mappings = {};
    _ref = fs.readdirSync(__dirname + '/plugins');
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      filename = _ref[_i];
      name = Path.basename(filename, Path.extname(filename));
      try {
        plugin = require('./plugins/' + filename);
        if (plugin.compile) {
          if (typeof plugin.source === 'string') plugin.source = [plugin.source];
          if (typeof plugin.target === 'string') plugin.target = [plugin.target];
          if (plugin.source) {
            _ref2 = plugin.source;
            for (_j = 0, _len2 = _ref2.length; _j < _len2; _j++) {
              ext = _ref2[_j];
              plugins['.' + ext] = plugin;
              mappings['.' + ext] = [''];
              if (plugin.target != null) {
                _ref3 = plugin.target;
                for (_k = 0, _len3 = _ref3.length; _k < _len3; _k++) {
                  te = _ref3[_k];
                  mappings['.' + ext].push('.' + te.replace(/^\./g, ''));
                }
              }
            }
          }
        }
      } catch (err) {

      }
    }
    MakePath.setmappings(mappings);
    return plugins;
  };

}).call(this);
