// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(names, options) {
    var err, name, _i, _j, _len, _len1, _names, _ref;
    _names = names;
    if (typeof names === 'string') {
      names = [names];
    }
    for (_i = 0, _len = names.length; _i < _len; _i++) {
      name = names[_i];
      if (((_ref = options.dependencies) != null ? _ref[name] : void 0) != null) {
        return options.dependencies[name];
      }
    }
    for (_j = 0, _len1 = names.length; _j < _len1; _j++) {
      name = names[_j];
      try {
        return require(name);
      } catch (_error) {
        err = _error;
      }
    }
    throw new Error("could not find module " + _names);
  };

}).call(this);
