// Generated by CoffeeScript 1.6.3
(function() {
  var try_require;

  try_require = function(mod) {
    var err, result;
    try {
      result = require(mod);
    } catch (_error) {
      err = _error;
      result = null;
    }
    return result;
  };

  module.exports = {
    source: 'coffee',
    target: 'js',
    compile: function(code, options, callback) {
      var coffee, err, key, plugin_config, val, _ref;
      try {
        coffee = null;
        if (coffee == null) {
          coffee = try_require('coffee-script');
        }
        if (coffee == null) {
          coffee = try_require('iced-coffee-script');
        }
        if (coffee == null) {
          throw new Error('could not find any coffee');
        }
        plugin_config = {
          filename: options.filename
        };
        if (options.plugin_config != null) {
          _ref = options.plugin_config;
          for (key in _ref) {
            val = _ref[key];
            plugin_config[key] = val;
          }
        }
        return callback(null, coffee.compile(code.toString('utf8'), plugin_config));
      } catch (_error) {
        err = _error;
        return callback(err);
      }
    }
  };

}).call(this);
