// Generated by CoffeeScript 1.2.1-pre
(function() {
  var try_require;

  try_require = function try_require(mod) {
    var result;
    try {
      result = require(mod);
    } catch (err) {
      result = null;
    }
    return result;
  };

  module.exports = {
    source: 'coffee',
    target: 'js',
    compile: function compile(code, options, callback) {
      var coffee;
      try {
        coffee = null;
        if (coffee == null) coffee = try_require('coffee-script');
        if (coffee == null) coffee = try_require('iced-coffee-script');
        if (coffee == null) throw new Error('could not find any coffee');
        return callback(null, coffee.compile(code, {
          filename: options.filename
        }));
      } catch (err) {
        return callback(err);
      }
    }
  };

}).call(this);
