// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = {
    source: 'coffee',
    target: 'js',
    compile: function(code, options, callback) {
      var coffee, err, key, plugin_config, val, _ref;
      try {
        coffee = require('../require')(['coffee-script', 'iced-coffee-script'], options);
        plugin_config = {
          filename: options.filename
        };
        if (options.plugin_config != null) {
          _ref = options.plugin_config;
          for (key in _ref) {
            val = _ref[key];
            plugin_config[key] = val;
          }
        }
        return callback(null, coffee.compile(code.toString('utf8'), plugin_config));
      } catch (_error) {
        err = _error;
        return callback(err);
      }
    }
  };

}).call(this);
