// Generated by CoffeeScript 1.2.1-pre
(function() {

  module.exports = {
    source: 'eco',
    compile: function compile(code, options, callback) {
      var eco, inlines;
      try {
        eco = require('eco');
        inlines = require('../inlines');
        code = eco.render(code, inlines.prepare(options));
        return inlines.call(code, function(err, newcode) {
          return callback(err, newcode);
        });
      } catch (err) {
        return callback(err);
      }
    }
  };

}).call(this);
