// Generated by CoffeeScript 1.4.0
(function() {

  module.exports = {
    source: 'eco',
    compile: function(code, options, callback) {
      var eco;
      try {
        eco = require('eco');
        return callback(null, eco.render(code));
      } catch (err) {
        return callback(err);
      }
    }
  };

}).call(this);
