// Generated by CoffeeScript 1.2.1-pre
(function() {

  module.exports = {
    source: 'ejs',
    compile: function compile(code, options, callback) {
      var ejs, inlines;
      try {
        ejs = require('ejs');
        inlines = require('../inlines');
        code = code.toString('utf8');
        code = ejs.render(code, inlines.prepare(options));
        return inlines.call(code, function(err, newcode) {
          return callback(err, newcode);
        });
      } catch (err) {
        return callback(err);
      }
    }
  };

}).call(this);
