// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = {
    source: 'ejs',
    compile: function(code, options, callback) {
      var ejs, err, inlines;
      try {
        ejs = require('../require')('ejs', options);
        inlines = require('../inlines');
        code = code.toString('utf8');
        code = ejs.render(code, inlines.prepare(options));
        return inlines.call(code, function(err, newcode) {
          return callback(err, newcode);
        });
      } catch (_error) {
        err = _error;
        return callback(err);
      }
    }
  };

}).call(this);
