// Generated by CoffeeScript 1.3.3
(function() {

  module.exports = {
    source: 'haml',
    target: 'html',
    compile: function compile(code, options, callback) {
      var Haml;
      try {
        Haml = require('haml');
        return callback(null, Haml(code.toString('utf8'))());
      } catch (err) {
        return callback(err);
      }
    }
  };

}).call(this);
