// Generated by CoffeeScript 1.4.0
(function() {

  module.exports = {
    source: 'iced',
    target: 'js',
    compile: function(code, options, callback) {
      var coffee;
      try {
        coffee = require('iced-coffee-script');
        return callback(null, coffee.compile(code.toString('utf8'), {
          filename: options.filename
        }));
      } catch (err) {
        return callback(err);
      }
    }
  };

}).call(this);
