// Generated by CoffeeScript 1.3.3
(function() {

  module.exports = {
    source: 'jade',
    target: 'js',
    compile: function compile(code, options, callback) {
      var jade, js;
      try {
        jade = require('jade');
        js = jade.compile(code, {
          filename: options.filename,
          compileDebug: false,
          client: true
        });
        return callback(null, js);
      } catch (err) {
        return callback(err);
      }
    }
  };

}).call(this);
