// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = {
    source: 'jade',
    target: 'js',
    compile: function(code, options, callback) {
      var err, jade, js, key, plugin_config, val, _ref;
      try {
        plugin_config = {
          filename: options.filename,
          compileDebug: false,
          client: true
        };
        if (options.plugin_config != null) {
          _ref = options.plugin_config;
          for (key in _ref) {
            val = _ref[key];
            plugin_config[key] = val;
          }
        }
        jade = require('../require')('jade', options);
        js = jade.compile(code, plugin_config);
        return callback(null, js);
      } catch (_error) {
        err = _error;
        return callback(err);
      }
    }
  };

}).call(this);
