// Generated by CoffeeScript 1.6.2
(function() {
  module.exports = {
    source: 'jade',
    target: 'html',
    compile: function(code, options, callback) {
      var err, jade, _ref;

      try {
        jade = require('jade');
        return jade.render(code, (_ref = options.plugin_config) != null ? _ref : {}, callback);
      } catch (_error) {
        err = _error;
        return callback(err);
      }
    }
  };

}).call(this);
