// Generated by CoffeeScript 1.2.1-pre
(function() {
  var Path, css_compiler, cssimport;

  cssimport = require('../cssimport');

  Path = require('path');

  css_compiler = function css_compiler(code, options, callback) {
    var less, parser, util;
    less = require('less');
    util = require('util');
    parser = new less.Parser({
      paths: [Path.dirname(options.filename), options.pipeline.builddir],
      filename: options.filename
    });
    return parser.parse(code, function(err, tree) {
      if (err) return callback(new Error(util.inspect(err)));
      return callback(null, tree.toCSS());
    });
  };

  module.exports = {
    source: 'less',
    target: 'css',
    compile: function compile(code, options, callback) {
      return cssimport.search_deps(code, options, 'less', function(err) {
        if (err) return callback(err);
        try {
          return css_compiler(code, options, callback);
        } catch (err) {
          return callback(err);
        }
      });
    }
  };

}).call(this);
