// Generated by CoffeeScript 1.3.3
(function() {
  var Path, css_compiler, cssimport, util;

  cssimport = require('../cssimport');

  Path = require('path');

  util = require('util');

  css_compiler = function css_compiler(code, options, callback) {
    var less, parser;
    try {
      less = require('less');
      parser = new less.Parser({
        paths: [Path.dirname(options.filename)],
        filename: options.filename
      });
      return parser.parse(code, function(err, tree) {
        try {
          if (err) {
            return callback(new Error(util.inspect(err)));
          }
          return callback(null, tree.toCSS());
        } catch (err) {
          if (err) {
            return callback(new Error(util.inspect(err)));
          }
        }
      });
    } catch (err) {
      if (err) {
        return callback(new Error(util.inspect(err)));
      }
    }
  };

  module.exports = {
    source: 'less',
    target: 'css',
    compile: function compile(code, options, callback) {
      return cssimport.search_deps(code, options, 'less', function(err, newfilename) {
        if (err) {
          return callback(err);
        }
        if (newfilename) {
          options.filename = newfilename;
        }
        return css_compiler(code, options, callback);
      });
    }
  };

}).call(this);
