// Generated by CoffeeScript 1.2.1-pre
(function() {
  var Path, css_compiler, cssimport, util;

  cssimport = require('../cssimport');

  Path = require('path');

  util = require('util');

  css_compiler = function css_compiler(code, options, callback) {
    var less, parser;
    less = require('less');
    parser = new less.Parser({
      paths: [Path.dirname(options.filename)],
      filename: options.filename
    });
    return parser.parse(code, function(err, tree) {
      if (err) return callback(new Error(util.inspect(err)));
      return callback(null, tree.toCSS());
    });
  };

  module.exports = {
    source: 'less',
    target: 'css',
    compile: function compile(code, options, callback) {
      return cssimport.search_deps(code, options, 'less', function(err, newfilename) {
        if (err) return callback(err);
        if (newfilename) options.filename = newfilename;
        try {
          return css_compiler(code, options, callback);
        } catch (err) {
          if (err) return callback(new Error(util.inspect(err)));
        }
      });
    }
  };

}).call(this);
