// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = {
    source: 'md',
    target: 'html',
    compile: function(code, options, callback) {
      var err, md;
      try {
        code = code.toString('utf8');
        md = require('node-markdown').Markdown;
        return callback(null, md(code));
      } catch (_error) {
        err = _error;
        return callback(err);
      }
    }
  };

}).call(this);
