// Generated by CoffeeScript 1.4.0
(function() {

  module.exports = {
    source: 'md',
    target: 'html',
    compile: function(code, options, callback) {
      var md;
      try {
        code = code.toString('utf8');
        md = require('node-markdown').Markdown;
        return callback(null, md(code));
      } catch (err) {
        return callback(err);
      }
    }
  };

}).call(this);
