// Generated by CoffeeScript 1.6.2
(function() {
  var Path, cssimport;

  cssimport = require('../cssimport');

  Path = require('path');

  module.exports = {
    source: 'styl',
    target: 'css',
    compile: function(code, options, callback) {
      return cssimport.search_deps(code, options, 'styl', function(err, newfilename) {
        var compiler, fn, idx, inlines, stylus, _ref;

        if (err) {
          return callback(err);
        }
        if (newfilename) {
          options.filename = newfilename;
        }
        try {
          stylus = require('stylus');
          inlines = require('../inlines');
          compiler = stylus(code);
          _ref = inlines.prepare(options);
          for (idx in _ref) {
            fn = _ref[idx];
            compiler.define(idx, fn);
          }
          return compiler.set('paths', [Path.dirname(options.filename)]).set({
            filename: options.filename
          }).render(function(err, res) {
            if (err) {
              return callback(err);
            }
            return inlines.call(res, callback);
          });
        } catch (_error) {
          err = _error;
          return callback(err);
        }
      });
    }
  };

}).call(this);
