// Generated by CoffeeScript 1.2.1-pre
(function() {
  var Path, cssimport;

  cssimport = require('../cssimport');

  Path = require('path');

  module.exports = {
    source: 'styl',
    target: 'css',
    compile: function compile(code, options, callback) {
      return cssimport.search_deps(code, options, 'styl', function(err, newfilename) {
        var stylus;
        if (err) return callback(err);
        if (newfilename) options.filename = newfilename;
        try {
          stylus = require('stylus');
          return stylus(code).set('paths', [Path.dirname(options.filename)]).set({
            filename: options.filename
          }).render(callback);
        } catch (err) {
          return callback(err);
        }
      });
    }
  };

}).call(this);
